# Generated by Django 4.2.3 on 2023-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_used',
            field=models.BooleanField(default=False, help_text='address in use or not'),
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, help_text='remark for the address', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, help_text='user id use the address', null=True),
        ),
    ]
