# Generated by Django 4.2.3 on 2023-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_address_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='resource',
            field=models.TextField(blank=True, help_text='resource app of the wallet or url', null=True),
        ),
    ]
